### ISSUE TITLE
Ubuntu vs. Debian

### ISSUE THREAD

**Issue by JonTheNiceGuy** [lugorguk/test-deploy#6]
My experiments thus far have followed the Debian path (as that's what we're currently using) and put us on the "current" stable Debian base. Moving to Ubuntu gives us the potential to get commercial support, should we struggle, and is also the distribution I personally use. I've had no issues with moving from LTS to LTS with Ubuntu in over 8 years, but I appreciate that Debian was a choice for a reason (which I was no part of).

I know AGK has ties with RedHat, so CentOS (or even RHEL, perhaps) is an option there too. I'd appreciate some thoughts before I throw much more effort into this!

**Comment by RalphCorderoy** [comment]
- Debian might attract support, should we need it, from those aligned to its ideals who would also probably support LUGs.
- Ubuntu has commercial support through Canonical but I can't see us ever needing or paying for it. :-)
- CentOS has the advantage of being upstream for RHEL so gets effort from Red Hat, but I've little personal experience of it. Not that I think that matters much once past the apt(1) v. dnf(1).

I'd be happy with any of the three. If Debian still have a habit of lagging behind their upstream then I'd favour one of the other two.

**Comment by gwestwood** [comment]
My background is primarily with Debian, although I can find my way around other distros from different bases such as Red Hat, etc., but I would generally prefer a Debian-based distro.

While I have nothing against a move to Ubuntu I can't see the LUG ever having funding to pay for support, so I don't think that should be a consideration in the choice of platform going forward.  If there are tools or features readily available on Ubuntu or another distro that would make it a better choice than Debian for management I can see that being a reason to switch though.

**Comment by RalphCorderoy** [comment]
https://en.wikipedia.org/wiki/List_of_Debian_releases#Release_table suggests it has recently been two years between Debian releases. Does a release get mainly security upgrades during that time, or will new features and whole new packages appear?

**Comment by JonTheNiceGuy** [comment]
So, I think the RH base is now off the table. I personally prefer Ubuntu over Debian, due to it's broader, more accessible support routes (e.g. askubuntu.com, Ubuntu IRC channels). I've also found there's generally more documentation about running services on Ubuntu, due to it's popularity, which in turn feeds itself!

I don't have a particular issue with Debian, I just feel that Ubuntu is a more polished and stable product... which I know is just confirmation bias! :wink:

**Comment by JonTheNiceGuy** [comment]
Thinking on it further. Ubuntu is generally similar enough to Debian that what I'm doing in Ansible at the moment won't make too much difference if I go with Debian or Ubuntu. Once we start talking to Andy about the next hosting, that'll be the point where we have to make a decision. I'm currently basing my work on a Debian base, so I think I'll probably stick with Debian until it becomes clear that one or the other is "better" for one reason or another. (Also, no-one has come out particularly in favour of either Debian or Ubuntu, so... let's stick with what we're doing :wink:)
